import Sidebar from "@/components/common/sidebar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "TMS",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex h-screen w-full bg-card">
      {/* Sidebar */}
      <Sidebar />

      {/* Page Content */}
      <main className="flex-1 overflow-y-auto">{children}</main>
    </div>
  );
}
