import NavigationWrapper from "@/components/common/navbarWrapper";
import Sidebar from "@/components/common/appSidebar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "TMS",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex h-screen w-full bg-gray-200">
      {/* Sidebar */}
      <Sidebar />

      <div className="flex flex-col flex-1">
        {/* Navigation */}
        <NavigationWrapper />

        {/* Page Content */}
        <main className="flex-1 overflow-y-auto">{children}</main>
      </div>
    </div>
  );
}
