import NavigationWrapper from "@/components/common/navbarWrapper";
import Sidebar from "@/components/common/appSidebar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "TMS",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="min-h-screen w-full bg-gray-200">
      {/* Sidebar */}
      <Sidebar />

      {/* Content Wrapper */}
      <div
        className="flex flex-col transition-all duration-300"
        style={{ marginLeft: "250px" }} // match expanded sidebar width
      >
        {/* Navigation */}
        <NavigationWrapper />

        {/* Page Content */}
        <main className="flex-1 overflow-y-auto p-4">{children}</main>
      </div>
    </div>
  );
}
