// data/leave-requests.ts
export interface LeaveRequest {
  id: string;
  employeeName: string;
  employeeId: string;
  leaveType: "FULL" | "SHORT_LEAVE" | "HALF_LEAVE";
  totalDays: number;
  dates: string; // e.g., "2025-11-13 - 2025-11-14"
  leaveStatus: "paid" | "unpaid";
  pmApproval: "APPROVED" | "PENDING" | "REJECTED";
  hrApproval: "APPROVED" | "PENDING" | "REJECTED";
}

export const dummyLeaveRequests: LeaveRequest[] = [
  {
    id: "1",
    employeeName: "John Doe",
    employeeId: "EMP001",
    leaveType: "FULL",
    totalDays: 2,
    dates: "2025-11-13 - 2025-11-14",
    leaveStatus: "paid",
    pmApproval: "APPROVED",
    hrApproval: "APPROVED",
  },
  {
    id: "2",
    employeeName: "Jane Smith",
    employeeId: "EMP002",
    leaveType: "HALF_LEAVE",
    totalDays: 1,
    dates: "2025-11-15",
    leaveStatus: "paid",
    pmApproval: "APPROVED",
    hrApproval: "PENDING",
  },
  {
    id: "3",
    employeeName: "Robert Johnson",
    employeeId: "EMP003",
    leaveType: "SHORT_LEAVE",
    totalDays: 1,
    dates: "2025-11-16",
    leaveStatus: "unpaid",
    pmApproval: "PENDING",
    hrApproval: "PENDING",
  },
  {
    id: "4",
    employeeName: "Alice Brown",
    employeeId: "EMP004",
    leaveType: "FULL",
    totalDays: 3,
    dates: "2025-11-20 - 2025-11-22",
    leaveStatus: "paid",
    pmApproval: "APPROVED",
    hrApproval: "APPROVED",
  },
  {
    id: "5",
    employeeName: "Michael Wilson",
    employeeId: "EMP005",
    leaveType: "HALF_LEAVE",
    totalDays: 1,
    dates: "2025-11-18",
    leaveStatus: "paid",
    pmApproval: "REJECTED",
    hrApproval: "REJECTED",
  },
  {
    id: "6",
    employeeName: "Sarah Davis",
    employeeId: "EMP006",
    leaveType: "FULL",
    totalDays: 1,
    dates: "2025-11-19",
    leaveStatus: "unpaid",
    pmApproval: "APPROVED",
    hrApproval: "PENDING",
  },
  {
    id: "7",
    employeeName: "David Miller",
    employeeId: "EMP007",
    leaveType: "SHORT_LEAVE",
    totalDays: 1,
    dates: "2025-11-21",
    leaveStatus: "paid",
    pmApproval: "APPROVED",
    hrApproval: "APPROVED",
  },
  {
    id: "8",
    employeeName: "Emily Taylor",
    employeeId: "EMP008",
    leaveType: "FULL",
    totalDays: 2,
    dates: "2025-11-25 - 2025-11-26",
    leaveStatus: "paid",
    pmApproval: "PENDING",
    hrApproval: "PENDING",
  },
  {
    id: "9",
    employeeName: "Thomas Anderson",
    employeeId: "EMP009",
    leaveType: "HALF_LEAVE",
    totalDays: 1,
    dates: "2025-11-27",
    leaveStatus: "unpaid",
    pmApproval: "APPROVED",
    hrApproval: "APPROVED",
  },
  {
    id: "10",
    employeeName: "Lisa White",
    employeeId: "EMP010",
    leaveType: "FULL",
    totalDays: 4,
    dates: "2025-11-28 - 2025-12-01",
    leaveStatus: "paid",
    pmApproval: "APPROVED",
    hrApproval: "PENDING",
  },
  {
    id: "11",
    employeeName: "James Moore",
    employeeId: "EMP011",
    leaveType: "SHORT_LEAVE",
    totalDays: 1,
    dates: "2025-12-02",
    leaveStatus: "paid",
    pmApproval: "PENDING",
    hrApproval: "PENDING",
  },
  {
    id: "12",
    employeeName: "Patricia Lee",
    employeeId: "EMP012",
    leaveType: "FULL",
    totalDays: 2,
    dates: "2025-12-03 - 2025-12-04",
    leaveStatus: "unpaid",
    pmApproval: "APPROVED",
    hrApproval: "APPROVED",
  },
  {
    id: "13",
    employeeName: "Christopher Harris",
    employeeId: "EMP013",
    leaveType: "HALF_LEAVE",
    totalDays: 1,
    dates: "2025-12-05",
    leaveStatus: "paid",
    pmApproval: "REJECTED",
    hrApproval: "REJECTED",
  },
  {
    id: "14",
    employeeName: "Amanda Clark",
    employeeId: "EMP014",
    leaveType: "FULL",
    totalDays: 3,
    dates: "2025-12-09 - 2025-12-11",
    leaveStatus: "paid",
    pmApproval: "APPROVED",
    hrApproval: "PENDING",
  },
  {
    id: "15",
    employeeName: "Matthew Lewis",
    employeeId: "EMP015",
    leaveType: "SHORT_LEAVE",
    totalDays: 1,
    dates: "2025-12-12",
    leaveStatus: "unpaid",
    pmApproval: "PENDING",
    hrApproval: "PENDING",
  },
];
